#!/usr/bin/env ruby

# wayland-scanner
# A driver program for the Wayland scanner.

require 'wayland/scanner'

abort("Usage: wayland-scanner xml_path destination_dir") unless (ARGV.length == 2)

xml_path, destination_path = ARGV

File.open(xml_path, 'r') do |xml|
  scanner = Wayland::Scanner::Scanner.new(xml, destination_path) #TODO: Ugh, fix namespace
  abort("Error: #{xml_path} failed validation.") unless scanner.xml_valid?
  scanner.scan!
end
